#!/bin/bash

#########################################
# Disable systemd-resolved for Evilginx
# 
# systemd-resolved conflicts with Evilginx's DNS server
# Both services try to use port 53
#########################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

log_step() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}▶${NC} $1"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

#########################################
# Main Function
#########################################

main() {
    log_step "Disabling systemd-resolved for Evilginx"
    
    # Check if systemd-resolved is installed
    if ! systemctl list-unit-files | grep -q systemd-resolved.service; then
        log_success "systemd-resolved is not installed - no action needed"
        log_info "Port 53 is available for Evilginx DNS server"
        exit 0
    fi
    
    log_info "systemd-resolved detected - will disable to free port 53"
    
    # Check if systemd-resolved is running
    if systemctl is-active --quiet systemd-resolved; then
        log_info "Stopping systemd-resolved service..."
        systemctl stop systemd-resolved
        log_success "systemd-resolved stopped"
    else
        log_info "systemd-resolved is not running"
    fi
    
    # Disable systemd-resolved from auto-starting
    if systemctl is-enabled --quiet systemd-resolved 2>/dev/null; then
        log_info "Disabling systemd-resolved from auto-start..."
        systemctl disable systemd-resolved
        log_success "systemd-resolved disabled"
    else
        log_info "systemd-resolved is already disabled"
    fi
    
    # Mask systemd-resolved to prevent it from being started
    log_info "Masking systemd-resolved to prevent activation..."
    systemctl mask systemd-resolved 2>/dev/null || true
    log_success "systemd-resolved masked"
    
    # Handle /etc/resolv.conf
    log_info "Configuring /etc/resolv.conf..."
    
    # Backup existing resolv.conf
    if [ -f /etc/resolv.conf ]; then
        cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
        log_info "Backed up existing /etc/resolv.conf"
    fi
    
    # Remove symlink if it exists
    if [ -L /etc/resolv.conf ]; then
        log_info "Removing /etc/resolv.conf symlink..."
        rm -f /etc/resolv.conf
        log_success "Symlink removed"
    fi
    
    # Create static resolv.conf with public DNS servers
    log_info "Creating static /etc/resolv.conf with public DNS servers..."
    cat > /etc/resolv.conf << 'EOF'
# Static DNS configuration for Evilginx
# Generated by disable-systemd-resolved.sh

# Google Public DNS
nameserver 8.8.8.8
nameserver 8.8.4.4

# Cloudflare DNS (backup)
nameserver 1.1.1.1
nameserver 1.0.0.1

# Options
options timeout:2
options attempts:3
options rotate
EOF
    
    log_success "Static /etc/resolv.conf created"
    
    # Make resolv.conf immutable to prevent systemd from modifying it
    log_info "Making /etc/resolv.conf immutable..."
    chattr +i /etc/resolv.conf 2>/dev/null || log_warning "Could not set immutable flag (chattr not available)"
    
    # Verify port 53 is free
    log_info "Verifying port 53 is available..."
    if lsof -i :53 >/dev/null 2>&1; then
        log_warning "Port 53 is still in use:"
        lsof -i :53
        log_info "You may need to reboot for changes to take full effect"
    else
        log_success "Port 53 is now available for Evilginx DNS server"
    fi
    
    # Show final status
    echo ""
    log_step "Summary"
    
    echo "systemd-resolved status:"
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        log_warning "Still running (reboot may be required)"
    else
        log_success "Stopped"
    fi
    
    if systemctl is-enabled --quiet systemd-resolved 2>/dev/null; then
        log_warning "Still enabled (should be disabled)"
    else
        log_success "Disabled from auto-start"
    fi
    
    echo ""
    echo "/etc/resolv.conf status:"
    if [ -L /etc/resolv.conf ]; then
        log_warning "Still a symlink: $(readlink -f /etc/resolv.conf)"
    else
        log_success "Static file (not symlinked)"
    fi
    
    echo ""
    log_success "systemd-resolved has been disabled successfully!"
    log_info "Port 53 is now available for Evilginx DNS server"
    
    echo ""
    log_info "Current DNS configuration:"
    cat /etc/resolv.conf
    
    echo ""
    log_info "If you need to undo these changes, run:"
    echo "  sudo chattr -i /etc/resolv.conf"
    echo "  sudo systemctl unmask systemd-resolved"
    echo "  sudo systemctl enable systemd-resolved"
    echo "  sudo systemctl start systemd-resolved"
    echo ""
}

# Run main function
main "$@"
